language: java
deploy:
  provider: releases
  api_key:
    secure: mrEs3eoqIwk7Lvet96K7pzKj+g7YvAJMyGaV3bNn+jA5UiCBESWWKiiTo4AivVEqosm3c8oCjgTMXkWbiZU4rDWp/sPMdvJwrVFJiqDqyLzPe2u6Gz6eJqTzz0MewlOISJU9PE+7OzDx/hkq1K6X29jN9YbixmmrYsgUhFqtDqudRlL2jidEv4aWi8kN69qI1zm2QBfM1lH2VGTJNHyEQ2i5xP+0U36XeUYN2bkMWL9wsBEhe345MYwCxDzr6c9xCvzeSrH7uBu7WKDPuYwBu/EHdGZC4lpP5LLMcRJ8+T8sW4WxPw03S9Y80f1KyqJr+mPzV9zB4H+z+hUqQw7oJB9cPCJdPb61u1J3UqTnv3i1Atg7KZ8Ft1YKsYMBOcV2r8OV59N3Y+n/gRUKrT2CedrmT4avdsX6lx++lXFryW3XjHJy9DslQLGa3W9v8xqe9qzKwXU6aHcLZohcRqZ0zCQOZssQ5bzyAYAi4+nYOwYMWlROkm3bzozCtYdzlra5FG/l9TCaw6C6nkjUqiNrKXcnOMoNS2QB9eFhColuKkEjxOXQhnut6ffzITjgQPZ7q0lPQdNBt7tomaY6t+zIhqhOuz2Bdp9sT4pDiAZ3dEQthc6J6gN8rtpijdFj/Fz4SE5z7GhzxR2TUoS1clrBz1dRRenJ/xlI+BvsZDEyVwQ=
  on:
    tags: true
    repo: cmosher01/teish
