language: java
deploy:
  provider: releases
  api_key:
    secure: 'Ne3cc+I/ZbtpkOnv3yr20ZxcqrdPXSt+z6TGwL3EbNe1AesohYwpJuJiK8Tv0RhzteDf59d0/TakCj+vF0RErAZGBZ50msuVmbbDJQ85ucM8SYFOzPMkVW4NgG/9LjQ0KjuHghq2htLWImusAV1EQg3B8suadcF+o7gAey0BmdBPMAcZEccDrt1A1nGxL9G0B04zkQCwJ5FBFfJD/QOPwbZkqpxF99G/ZaA10ENgkgFBGWkLCKwb32EWodZrUwSyMYOBGydYBT7biLiepjF0ilNu3st4li9vD61b6Sor6iBGBWS0wrO98tEPjTgbhcJdusxvo8ixhqidn5jeBEWcAqo0r3hBf6HLTycZG/EzZpcXWXJbOKvKlV/NKzAmomYp5p6qGQczD9ZhZjRlktiBUqmbMoUPOvCLOxvyznYEFEla/Ob/fSZ8TCjv7nJS2FED0x08dpl6D2pfHu+F4f+jS0ty5PAlRIQdNzRMKcLCXTiuPM80ecagJyCdJuBbu7vJL2Hvxj1Z7vRpKJFyIyrIIrrEL4yqmZGd4CVA8QCShpZepppyrDsOdF92rgn+J9pV8Un9aoKQovO5WVMzUH5Dg6SyQ5oyoqstv9CDW9sQV3tM2TBm/0X7pnpyMFTIK4qPuuyN3IFZtiBaYmcx9mb2qfphGmj8oAjFgFe6aY+aRlM='
  file: 'src/main/resources/teish.*'
  tags: true
  on:
    repo: 'cmosher01/teish'
